// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmY6keFuInzmNbt4qI9MhdYyiWn-21-VY',
    appId: '1:244938291730:web:0c6026aed41dbc18e7b6cb',
    messagingSenderId: '244938291730',
    projectId: 'ditonton-d1376',
    authDomain: 'ditonton-d1376.firebaseapp.com',
    storageBucket: 'ditonton-d1376.firebasestorage.app',
    measurementId: 'G-JFJDPJ8BKJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABl9IwQj6ZNJIjrIN3rjLwfFfInN7WuR8',
    appId: '1:244938291730:android:531e7325c21fbf8ee7b6cb',
    messagingSenderId: '244938291730',
    projectId: 'ditonton-d1376',
    storageBucket: 'ditonton-d1376.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2FD43sX7eWntCaMLkm39oY_z4GSuiCR4',
    appId: '1:244938291730:ios:f3e7b6ccfa9d3f28e7b6cb',
    messagingSenderId: '244938291730',
    projectId: 'ditonton-d1376',
    storageBucket: 'ditonton-d1376.firebasestorage.app',
    iosBundleId: 'com.dicoding.ditonton',
  );
}
